server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: 13579Thiru@p
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
